#!/bin/bash

# Copyright 2019 Spotify AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ROOT=$(dirname $(dirname $0))

for proto in $ROOT/proto/*.proto; do
    protoc --java_out $ROOT/src/main/java $proto
done

sed -i 's/com\.google\.protobuf/com.google.protobuf250/g' $(find $ROOT/src/main/java/com/spotify/ffwd -name '*.java')
