#!/bin/bash

ROOT=$(dirname $(dirname $0))

for proto in $ROOT/proto/*.proto; do
    protoc --java_out $ROOT/src/main/java $proto
done

sed -i 's/com\.google\.protobuf/com.google.protobuf250/g' $(find $ROOT/src/main/java/com/spotify/ffwd -name '*.java')
